### ISSUE TITLE
Résolution des problèmes

### ISSUE THREAD

**Issue by Julien-Martin** [KevinDerda/Porfolio#3]
`check` n'existe pas (utilise `add`, `remove` ou `toggle`)
https://github.com/KevinDerda/Porfolio/blob/6b6b663d0e5b819ba442ad07f93703b5c959cefc/myScript.js#L13
Pour la bannière utilise plutôt :
`cookieBanner.style.display = 'none'` pour cacher
`cookieBanner.style.display = 'block'` pour afficher

Fichier introuvable
https://github.com/KevinDerda/Porfolio/blob/6b6b663d0e5b819ba442ad07f93703b5c959cefc/KDsite.html#L54

Fichier introuvable
https://github.com/KevinDerda/Porfolio/blob/6b6b663d0e5b819ba442ad07f93703b5c959cefc/KDsite.html#L506

**Comment by KevinDerda** [comment]
Résolu
